import { defaultModels } from './default-models';
import { ProviderRegistryEntry, ProviderType } from './provider-types';

export const providerRegistry: Record<ProviderType, ProviderRegistryEntry> = {
    openai: {
        label: 'OpenAI',
        category: 'byok',
        requiresApiKey: true,
        supportsBaseUrl: false,
        supportsModelSync: true,
        defaultModels: defaultModels.openai,
    },
    anthropic: {
        label: 'Anthropic',
        category: 'byok',
        requiresApiKey: true,
        supportsBaseUrl: false,
        supportsModelSync: false,
        defaultModels: defaultModels.anthropic,
    },
    google: {
        label: 'Google Gemini',
        category: 'byok',
        requiresApiKey: true,
        supportsBaseUrl: false,
        supportsModelSync: false,
        defaultModels: defaultModels.google,
    },
    groq: {
        label: 'Groq',
        category: 'byok',
        requiresApiKey: true,
        supportsBaseUrl: false,
        supportsModelSync: true,
        defaultModels: defaultModels.groq,
    },
    mistral: {
        label: 'Mistral',
        category: 'byok',
        requiresApiKey: true,
        supportsBaseUrl: false,
        supportsModelSync: true,
        defaultModels: defaultModels.mistral,
    },
    cohere: {
        label: 'Cohere',
        category: 'byok',
        requiresApiKey: true,
        supportsBaseUrl: false,
        supportsModelSync: false,
        defaultModels: defaultModels.cohere,
    },
    xai: {
        label: 'xAI',
        category: 'byok',
        requiresApiKey: true,
        supportsBaseUrl: true,
        defaultBaseUrl: 'https://api.x.ai/v1',
        supportsModelSync: true,
        isOpenAICompatible: true,
        defaultModels: defaultModels.xai,
    },
    deepseek: {
        label: 'DeepSeek',
        category: 'byok',
        requiresApiKey: true,
        supportsBaseUrl: true,
        defaultBaseUrl: 'https://api.deepseek.com',
        supportsModelSync: true,
        isOpenAICompatible: true,
        defaultModels: defaultModels.deepseek,
    },
    perplexity: {
        label: 'Perplexity',
        category: 'byok',
        requiresApiKey: true,
        supportsBaseUrl: true,
        defaultBaseUrl: 'https://api.perplexity.ai',
        supportsModelSync: false,
        isOpenAICompatible: true,
        defaultModels: defaultModels.perplexity,
    },
    together: {
        label: 'Together AI',
        category: 'byok',
        requiresApiKey: true,
        supportsBaseUrl: true,
        defaultBaseUrl: 'https://api.together.xyz/v1',
        supportsModelSync: true,
        isOpenAICompatible: true,
        defaultModels: defaultModels.together,
    },
    fireworks: {
        label: 'Fireworks',
        category: 'byok',
        requiresApiKey: true,
        supportsBaseUrl: true,
        defaultBaseUrl: 'https://api.fireworks.ai/inference/v1',
        supportsModelSync: true,
        isOpenAICompatible: true,
        defaultModels: defaultModels.fireworks,
    },
    cerebras: {
        label: 'Cerebras',
        category: 'byok',
        requiresApiKey: true,
        supportsBaseUrl: true,
        defaultBaseUrl: 'https://api.cerebras.ai/v1',
        supportsModelSync: false,
        isOpenAICompatible: true,
        defaultModels: defaultModels.cerebras,
    },
    openrouter: {
        label: 'OpenRouter',
        category: 'byok',
        requiresApiKey: true,
        supportsBaseUrl: true,
        defaultBaseUrl: 'https://openrouter.ai/api/v1',
        supportsModelSync: true,
        isOpenAICompatible: true,
        isGateway: true,
        defaultModels: defaultModels.openrouter,
    },
    ollama: {
        label: 'Ollama',
        category: 'local',
        requiresApiKey: false,
        supportsBaseUrl: true,
        defaultBaseUrl: 'http://localhost:11434',
        supportsModelSync: true,
        isLocal: true,
        defaultModels: defaultModels.ollama,
    },
    lmstudio: {
        label: 'LM Studio',
        category: 'local',
        requiresApiKey: false,
        supportsBaseUrl: true,
        defaultBaseUrl: 'http://localhost:1234/v1',
        supportsModelSync: true,
        isOpenAICompatible: true,
        isLocal: true,
        defaultModels: defaultModels.lmstudio,
    },
    localai: {
        label: 'LocalAI',
        category: 'local',
        requiresApiKey: false,
        supportsBaseUrl: true,
        defaultBaseUrl: 'http://localhost:8080/v1',
        supportsModelSync: true,
        isOpenAICompatible: true,
        isLocal: true,
        defaultModels: defaultModels.localai,
    },
    vllm: {
        label: 'vLLM',
        category: 'local',
        requiresApiKey: false,
        supportsBaseUrl: true,
        defaultBaseUrl: 'http://localhost:8000/v1',
        supportsModelSync: true,
        isOpenAICompatible: true,
        isLocal: true,
        defaultModels: defaultModels.vllm,
    },
    llamacpp: {
        label: 'llama.cpp server',
        category: 'local',
        requiresApiKey: false,
        supportsBaseUrl: true,
        defaultBaseUrl: 'http://localhost:8080/v1',
        supportsModelSync: true,
        isOpenAICompatible: true,
        isLocal: true,
        defaultModels: defaultModels.llamacpp,
    },
    'custom-openai-compatible': {
        label: 'Custom OpenAI-compatible',
        category: 'local',
        requiresApiKey: false,
        supportsBaseUrl: true,
        supportsModelSync: true,
        isOpenAICompatible: true,
        defaultModels: defaultModels['custom-openai-compatible'],
    },
};
